/**
 * Generating and installing the hook configuration.
 *
 * Two hard rules from the spec govern this file:
 *
 *  - The only paths Decagram Council writes under `<config>` are its own hook scripts.
 *  - Settings edits require explicit user approval, so the generator produces a
 *    fragment and a diff-ready merged document; writing is a separate, opt-in call.
 *
 * The merge is conservative: existing entries are preserved and Decagram Council's own
 * entries are replaced by identity, so re-running never accumulates duplicates
 * and never removes a hook the user configured themselves.
 */

import { mkdir, writeFile, readFile, rename, chmod } from 'node:fs/promises';
import * as path from 'node:path';
import type { ClaudePaths } from '../paths.js';
import { DECAGRAM_COUNCIL_HOOK_EVENTS, type DecagramCouncilHookEvent } from './events.js';
import { POWERSHELL_HOOK_FILENAME, powershellHookScript } from './scripts.js';

/** Marks an entry as Decagram Council's, so regeneration can replace exactly its own. */
export const DECAGRAM_COUNCIL_HOOK_MARKER = 'decagram-council-hook';
const LEGACY_HOOK_MARKER = 'muster-hook';
const LEGACY_GATE_MARKER = 'muster-story-gate';
const CURRENT_GATE_MARKER = 'decagram-council-story-gate';
const LEGACY_HOOK_FILENAMES = ['muster-hook.sh', 'muster-hook.ps1'] as const;

export interface CommandHookHandler {
  readonly type: 'command';
  readonly command: string;
  readonly shell?: 'powershell';
  readonly async?: boolean;
  readonly timeout?: number;
  readonly statusMessage?: string;
}

export interface HookMatcherGroup {
  readonly matcher?: string;
  readonly hooks: readonly CommandHookHandler[];
}

export type HooksConfig = Partial<Record<string, HookMatcherGroup[]>>;

/**
 * Matchers per event.
 *
 * Notification is filtered to the two types the spec names plus the states
 * where a session is parked on a person. Matcher syntax: a plain list separated
 * by `|` is an exact-match list, not a regex.
 */
const EVENT_MATCHERS: Partial<Record<DecagramCouncilHookEvent, string>> = {
  Notification: 'agent_needs_input|agent_completed|permission_prompt|elicitation_dialog',
};

/**
 * Builds the `hooks` fragment for settings.json.
 *
 * Every entry is `async: true`: these hooks only observe, and running them
 * inline would add a network round trip to each agent turn. Async delivery is
 * exactly the "hooks are the fast path, never the only path" contract — a
 * dropped delivery is corrected by the next reconciliation poll.
 */
export function generateHookConfig(paths: ClaudePaths): HooksConfig {
  const script = path.join(paths.hookScriptsDir(), POWERSHELL_HOOK_FILENAME);
  const escapedScript = script.replaceAll("'", "''");

  const config: HooksConfig = {};
  for (const event of DECAGRAM_COUNCIL_HOOK_EVENTS) {
    const handler: CommandHookHandler = {
      type: 'command',
      // Hook `shell` is ignored when `args` is present, and Windows cannot exec
      // a .ps1 file directly. Shell form is intentional here; single-quoting
      // keeps profile paths with spaces or metacharacters intact.
      command: `& '${escapedScript}' '${event}'`,
      shell: 'powershell',
      async: true,
      timeout: 10,
      statusMessage: DECAGRAM_COUNCIL_HOOK_MARKER,
    };

    const matcher = EVENT_MATCHERS[event];
    config[event] = [matcher === undefined ? { hooks: [handler] } : { matcher, hooks: [handler] }];
  }

  return config;
}

/** True when a handler was generated by Decagram Council and may be replaced. */
function isDecagramCouncilHandler(handler: unknown): boolean {
  if (typeof handler !== 'object' || handler === null) return false;
  const record = handler as Record<string, unknown>;
  if (
    record['statusMessage'] === DECAGRAM_COUNCIL_HOOK_MARKER ||
    record['statusMessage'] === CURRENT_GATE_MARKER ||
    // Migration path added 2026-07-26. Keep until old installs are no longer supported.
    record['statusMessage'] === LEGACY_HOOK_MARKER ||
    record['statusMessage'] === LEGACY_GATE_MARKER
  ) {
    return true;
  }
  const command = record['command'];
  return (
    typeof command === 'string' &&
    (command.includes(POWERSHELL_HOOK_FILENAME) ||
      LEGACY_HOOK_FILENAMES.some((filename) => command.includes(filename)))
  );
}

/**
 * Merges the generated config into existing settings.
 *
 * Pure: returns a new document so the caller can diff it, show it, and only
 * then write. Groups are matched on `matcher` so a user's own entry for the
 * same event survives untouched.
 */
export function mergeHookConfig(
  settings: Record<string, unknown>,
  generated: HooksConfig,
): Record<string, unknown> {
  const existingHooks =
    typeof settings['hooks'] === 'object' && settings['hooks'] !== null
      ? ({ ...(settings['hooks'] as Record<string, unknown>) })
      : {};

  for (const [event, groups] of Object.entries(generated)) {
    if (groups === undefined) continue;

    const priorRaw = existingHooks[event];
    const prior = Array.isArray(priorRaw) ? (priorRaw as HookMatcherGroup[]) : [];

    // Drop Decagram Council's previous handlers, keeping every other hook in place.
    const preserved: HookMatcherGroup[] = [];
    for (const group of prior) {
      if (typeof group !== 'object' || group === null) continue;
      const handlers = Array.isArray(group.hooks) ? group.hooks : [];
      const kept = handlers.filter((handler) => !isDecagramCouncilHandler(handler));
      if (kept.length > 0) preserved.push({ ...group, hooks: kept });
    }

    // Fold ours into a group with the same matcher when one already exists, so
    // the file stays readable instead of growing parallel groups.
    const merged = [...preserved];
    for (const group of groups) {
      const index = merged.findIndex((candidate) => candidate.matcher === group.matcher);
      if (index === -1) {
        merged.push(group);
      } else {
        const target = merged[index];
        if (target !== undefined) {
          merged[index] = { ...target, hooks: [...target.hooks, ...group.hooks] };
        }
      }
    }

    existingHooks[event] = merged;
  }

  return { ...settings, hooks: existingHooks };
}

/**
 * Removes Decagram Council's entries from settings, leaving everything else alone.
 * Backs the uninstall action.
 */
export function removeHookConfig(settings: Record<string, unknown>): Record<string, unknown> {
  const hooksRaw = settings['hooks'];
  if (typeof hooksRaw !== 'object' || hooksRaw === null) return settings;

  const hooks: Record<string, unknown> = {};
  for (const [event, groupsRaw] of Object.entries(hooksRaw as Record<string, unknown>)) {
    if (!Array.isArray(groupsRaw)) {
      hooks[event] = groupsRaw;
      continue;
    }
    const groups: HookMatcherGroup[] = [];
    for (const group of groupsRaw as HookMatcherGroup[]) {
      if (typeof group !== 'object' || group === null) continue;
      const kept = (Array.isArray(group.hooks) ? group.hooks : []).filter((h) => !isDecagramCouncilHandler(h));
      if (kept.length > 0) groups.push({ ...group, hooks: kept });
    }
    if (groups.length > 0) hooks[event] = groups;
  }

  return { ...settings, hooks };
}

export interface HookInstallPlan {
  /** Windows PowerShell scripts to write. */
  readonly scripts: readonly { path: string; contents: string; mode: number }[];
  readonly settingsFile: string;
  readonly currentSettings: Record<string, unknown>;
  readonly mergedSettings: Record<string, unknown>;
  /** JSON the user is asked to approve. */
  readonly diffPreview: string;
  /** True when settings already contain exactly this configuration. */
  readonly settingsUnchanged: boolean;
}

async function readSettings(file: string): Promise<Record<string, unknown>> {
  try {
    const parsed: unknown = JSON.parse(await readFile(file, 'utf8'));
    return typeof parsed === 'object' && parsed !== null ? (parsed as Record<string, unknown>) : {};
  } catch {
    // Missing or unreadable settings are treated as empty; the write path never
    // clobbers a file it could not parse (see installHooks).
    return {};
  }
}

/**
 * Prepares the install without touching disk.
 *
 * Decagram Council is Windows-only, so the generated configuration always
 * selects PowerShell and installs only the PowerShell forwarder.
 */
export async function planHookInstall(paths: ClaudePaths): Promise<HookInstallPlan> {
  const current = await readSettings(paths.settingsFile());
  const generated = generateHookConfig(paths);
  const merged = mergeHookConfig(current, generated);

  return {
    scripts: [
      {
        path: path.join(paths.hookScriptsDir(), POWERSHELL_HOOK_FILENAME),
        contents: powershellHookScript(),
        mode: 0o644,
      },
    ],
    settingsFile: paths.settingsFile(),
    currentSettings: current,
    mergedSettings: merged,
    diffPreview: JSON.stringify({ hooks: merged['hooks'] }, null, 2),
    settingsUnchanged: JSON.stringify(current['hooks']) === JSON.stringify(merged['hooks']),
  };
}

export interface InstallResult {
  readonly scriptsWritten: readonly string[];
  readonly settingsWritten: boolean;
}

/**
 * Executes a plan. Call only after the user has approved `diffPreview`.
 *
 * Scripts always install (they are Decagram Council's own files). Settings are written
 * only when `approveSettingsEdit` is true, and refuse to proceed if the file
 * exists but could not be parsed — overwriting an unreadable settings file
 * would destroy configuration this app has no business touching.
 */
export async function installHooks(
  plan: HookInstallPlan,
  options: { approveSettingsEdit: boolean },
): Promise<InstallResult> {
  const written: string[] = [];

  for (const script of plan.scripts) {
    await mkdir(path.dirname(script.path), { recursive: true });
    await writeFile(script.path, script.contents, 'utf8');
    // Kept for deterministic plans; Windows ignores POSIX mode bits.
    await chmod(script.path, script.mode).catch(() => undefined);
    written.push(script.path);
  }

  if (!options.approveSettingsEdit || plan.settingsUnchanged) {
    return { scriptsWritten: written, settingsWritten: false };
  }

  let existingText: string | undefined;
  try {
    existingText = await readFile(plan.settingsFile, 'utf8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
  }
  if (existingText !== undefined) {
    try {
      JSON.parse(existingText);
    } catch {
      throw new Error(
        `${plan.settingsFile} is not valid JSON; refusing to overwrite it. Fix or move the file, then retry.`,
      );
    }
  }

  await mkdir(path.dirname(plan.settingsFile), { recursive: true });
  const temp = `${plan.settingsFile}.decagram.tmp`;
  await writeFile(temp, `${JSON.stringify(plan.mergedSettings, null, 2)}\n`, 'utf8');
  await rename(temp, plan.settingsFile);

  return { scriptsWritten: written, settingsWritten: true };
}
