/**
 * The paired bash / PowerShell hook scripts.
 *
 * These forward a hook payload to the app's loopback receiver. They are the one
 * thing Muster writes into the Claude config directory, under `<config>/muster/hooks/`.
 *
 * WHY SCRIPTS RATHER THAN `"type": "http"`: v2.1.220 does support HTTP hooks,
 * gated by the `allowedHttpHookUrls` setting. But an HTTP hook needs a literal
 * URL in settings.json, and the receiver binds an ephemeral port that changes
 * every launch — which would mean rewriting the user's settings on every start.
 * A script reads the port at fire time, so settings are written once.
 *
 * Both dialects hold to the same three rules:
 *   1. Always exit 0. These are observation hooks; a broken receiver must never
 *      block or fail an agent's turn. (Gate scripts are the deliberate
 *      exception — see scripts/gates/.)
 *   2. Never write to stdout. Hook stdout is fed back into the session.
 *   3. Give up fast. The app may not be running.
 */

/** Seconds a forwarder will wait on the receiver before abandoning the post. */
const CURL_TIMEOUT_SECONDS = 3;

/**
 * bash forwarder — macOS and Linux.
 *
 * Parses the descriptor with sed rather than jq: jq is not installed by default
 * on macOS, and this file is written by us in a known pretty-printed shape.
 */
export function bashHookScript(): string {
  return `#!/usr/bin/env bash
# Generated by Muster. Forwards a Claude Code hook payload to the local app.
# Regenerated on demand — edits here are overwritten.
#
# Usage: muster-hook.sh <EventName>   (payload arrives on stdin)
set -u

EVENT="\${1:-}"
[ -z "$EVENT" ] && exit 0

CONFIG_DIR="\${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
DESCRIPTOR="$CONFIG_DIR/muster/receiver.json"

# No descriptor means the app is not running. Nothing to report; not an error.
[ -f "$DESCRIPTOR" ] || exit 0

PORT=$(sed -n 's/.*"port"[[:space:]]*:[[:space:]]*\\([0-9]*\\).*/\\1/p' "$DESCRIPTOR" | head -n 1)
SECRET=$(sed -n 's/.*"secret"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p' "$DESCRIPTOR" | head -n 1)

[ -z "$PORT" ] && exit 0
[ -z "$SECRET" ] && exit 0

PAYLOAD=$(cat)

# --max-time bounds the whole request: a hung receiver must not stall the turn.
# Output is discarded so nothing is echoed back into the session.
curl --silent --show-error --max-time ${CURL_TIMEOUT_SECONDS} \\
  --request POST \\
  --header 'content-type: application/json' \\
  --header "x-muster-secret: $SECRET" \\
  --data-binary "$PAYLOAD" \\
  "http://127.0.0.1:$PORT/hook/$EVENT" >/dev/null 2>&1

# Always succeed: this hook observes, it never gates.
exit 0
`;
}

/**
 * PowerShell forwarder — Windows.
 *
 * Configured with `"shell": "powershell"`, which the settings schema confirms
 * as one of the two accepted values alongside `bash`.
 */
export function powershellHookScript(): string {
  return `#Requires -Version 5.1
# Generated by Muster. Forwards a Claude Code hook payload to the local app.
# Regenerated on demand - edits here are overwritten.
#
# Usage: muster-hook.ps1 <EventName>   (payload arrives on stdin)

param([Parameter(Position = 0)][string]$Event)

$ErrorActionPreference = 'SilentlyContinue'

if ([string]::IsNullOrWhiteSpace($Event)) { exit 0 }

$configDir = $env:CLAUDE_CONFIG_DIR
if ([string]::IsNullOrWhiteSpace($configDir)) {
    $configDir = Join-Path $env:USERPROFILE '.claude'
}
$descriptor = Join-Path (Join-Path $configDir 'muster') 'receiver.json'

# No descriptor means the app is not running. Nothing to report; not an error.
if (-not (Test-Path -LiteralPath $descriptor)) { exit 0 }

try {
    $info = Get-Content -LiteralPath $descriptor -Raw | ConvertFrom-Json
} catch {
    exit 0
}

if (-not $info.port -or -not $info.secret) { exit 0 }

# Read the payload as raw text and post the bytes unchanged, so the receiver
# sees exactly what Claude Code emitted.
$payload = [Console]::In.ReadToEnd()
if ([string]::IsNullOrWhiteSpace($payload)) { $payload = '{}' }

try {
    Invoke-RestMethod \`
        -Uri ("http://127.0.0.1:{0}/hook/{1}" -f $info.port, $Event) \`
        -Method Post \`
        -ContentType 'application/json' \`
        -Headers @{ 'x-muster-secret' = $info.secret } \`
        -Body ([System.Text.Encoding]::UTF8.GetBytes($payload)) \`
        -TimeoutSec ${CURL_TIMEOUT_SECONDS} | Out-Null
} catch {
    # App closed mid-turn, or the port moved. Reconciliation polling covers it.
}

# Always succeed: this hook observes, it never gates.
exit 0
`;
}

export const BASH_HOOK_FILENAME = 'muster-hook.sh';
export const POWERSHELL_HOOK_FILENAME = 'muster-hook.ps1';
