/**
 * The Windows PowerShell hook forwarder.
 *
 * It forwards a hook payload to the app's loopback receiver. This is the only
 * generated script Decagram Council writes under
 * `<config>/decagram-council/hooks/`.
 *
 * A script is used instead of an HTTP hook because the receiver binds an
 * ephemeral port. The script reads the current port from receiver.json, so the
 * user's settings do not need to be rewritten on every launch.
 *
 * The forwarder always exits 0, never writes to stdout, and gives up quickly.
 * It observes agent activity; it never gates it.
 */

const REQUEST_TIMEOUT_SECONDS = 3;

export function powershellHookScript(): string {
  return `#Requires -Version 5.1
# Generated by Decagram Council. Forwards a Claude Code hook payload to the app.
# Regenerated on demand - edits here are overwritten.
#
# Usage: decagram-council-hook.ps1 <EventName> (payload arrives on stdin)

param([Parameter(Position = 0)][string]$Event)

$ErrorActionPreference = 'SilentlyContinue'

if ([string]::IsNullOrWhiteSpace($Event)) { exit 0 }

$configDir = $env:CLAUDE_CONFIG_DIR
if ([string]::IsNullOrWhiteSpace($configDir)) {
    $configDir = Join-Path $env:USERPROFILE '.claude'
}
$descriptor = Join-Path (Join-Path $configDir 'decagram-council') 'receiver.json'

if (-not (Test-Path -LiteralPath $descriptor)) { exit 0 }

try {
    $info = Get-Content -LiteralPath $descriptor -Raw | ConvertFrom-Json
} catch {
    exit 0
}

if (-not $info.port -or -not $info.secret) { exit 0 }

$payload = [Console]::In.ReadToEnd()
if ([string]::IsNullOrWhiteSpace($payload)) { $payload = '{}' }

try {
    Invoke-RestMethod \`
        -Uri ("http://127.0.0.1:{0}/hook/{1}" -f $info.port, $Event) \`
        -Method Post \`
        -ContentType 'application/json' \`
        -Headers @{ 'x-decagram-council-secret' = $info.secret } \`
        -Body ([System.Text.Encoding]::UTF8.GetBytes($payload)) \`
        -TimeoutSec ${REQUEST_TIMEOUT_SECONDS} | Out-Null
} catch {
    # The app may have closed between hook dispatch and delivery. Polling
    # reconciles state when it returns.
}

exit 0
`;
}

export const POWERSHELL_HOOK_FILENAME = 'decagram-council-hook.ps1';
